version: ~> 1.0
os: linux
dist: xenial
language: node_js
node_js: 14
services:
  - docker
cache:
  directories:
    - docker_images
before_install:
  - docker load -i docker_images/images.tar || true
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
before_script:
  - echo "TOPIC=test-hyperswarm-${TRAVIS_BUILD_ID}-${TRAVIS_JOB_ID}" > .env
script:
  - ./test.sh
