version: 1

update_configs:
  # docker deps
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"

  # node deps
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
